# .streamlit/config.toml
[theme]
base="light"
primaryColor="#FF7A18"         # Saxon orange
backgroundColor="#FAF8F5"      # warm neutral background
secondaryBackgroundColor="#FFFFFF"
textColor="#17223B"            # deep navy text
font="sans serif"              # Streamlit system sans

[client]
showSidebarNavigation = true
